version: '3.8'

services:
  app:
    build: .
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DATABASE_URL=postgresql://${DATABASE_USER:-postgres}:${DATABASE_PASSWORD:-postgres}@db:5432/${DATABASE_NAME:-osireon}
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    restart: unless-stopped

  db:
    image: postgres:14
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DATABASE_USER:-postgres}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-postgres}
      - POSTGRES_DB=${DATABASE_NAME:-osireon}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
